"""
HAA 73: Money Matters — Course readings with PDF files, real extracted passages,
culture tags, and descriptions for AI relevance matching.
"""

READINGS = [
    # ── Week 1: Introduction ────────────────────────────────────────────────
    {
        "id": "meikle-1994",
        "authors": "S. Meikle",
        "title": "Aristotle on Money",
        "citation": "S. Meikle, 'Aristotle on Money,' Phronesis Vol. 39/No. 1 (1994), pp. 26-44.",
        "file": "Money according to Aristotle (2).pdf",
        "key_passage": "Money came into existence in the first place, he says, in order to make this sort of exchange easier, by allowing the sale (C-M) and the purchase (M-C) to be separated in time and place. This use of money is 'necessary and laudable' because it is a means subordinate to a natural end. It is to be contrasted with unnatural chrematistike (M-C-M) and obolostatike (M-M) whose end is not need or 'having enough', but the accumulation of money, and this has no natural terminus; 'in this art of wealth-getting there is no limit of the end.'",
        "passage_source": "pp. 3–4",
        "cultures": ["Greek", "Hellenistic"],
        "date_range": [-400, -300],
        "topics": ["money theory", "philosophy", "value", "exchange"],
        "week": 1,
        "description": "Aristotle's philosophical analysis of money as measure of value and medium of exchange; situates Greek coinage within broader questions of justice, price, and the good life.",
    },
    {
        "id": "georganteli-2008-numismatics",
        "authors": "E. Georganteli",
        "title": "Numismatics (Oxford Handbook of Byzantine Studies)",
        "citation": "E. Georganteli, 'Numismatics,' in Oxford Handbook of Byzantine Studies (Oxford: Oxford University Press, 2008), pp. 157-175.",
        "file": "Numismatics, OHBS 2008 (1).pdf",
        "key_passage": "Numismatics is the study of coins in terms of metrology, metallic value, fineness, mint attribution, and chronology, but also the study of realities in which coinage has been embedded, namely socio-economic history, political ideology, and religious practices, language, and art. Oresme's Traité des monnaies summarizes the principles and use of coinage in society; coins are instruments of exchange of natural riches, they are easy to handle, light enough to carry, conform to a certain standard, and while having a stamp of authority approved and organized by the ruling power, they do not belong to a single individual, but to the entire community and its every member.",
        "passage_source": "pp. 2–3",
        "cultures": ["Byzantine"],
        "date_range": [330, 1453],
        "topics": ["numismatics methodology", "Byzantine coins", "solidus", "follis"],
        "week": 1,
        "description": "Overview of Byzantine numismatics as a scholarly discipline; covers coin types from Constantine to 1453, minting practices, and coins as historical documents.",
    },
    {
        "id": "georganteli-numismatics-2",
        "authors": "E. Georganteli",
        "title": "Byzantine Numismatics",
        "citation": "E. Georganteli, 'Numismatics' (Byzantine coinage overview).",
        "file": "Georganteli Numismatics (2).pdf",
        "key_passage": "The history of Byzantine coinage starts conventionally with the reign of Anastasios, who in 491 introduced a currency reform as part of a wider platform of measures, designed to improve economic life and practices in the eastern Roman empire. Christian symbols, such as the cross and the Chi-Rho, appear increasingly on both the obverse and reverse of the coins, but it is really in the design of the gold currency that the establishment of Christianity is best reflected. Reverse images of Roman emperors spearing, or stepping on humiliated enemies gave way gradually to representations of Constantinople, the Christian new Rome of the empire, while the old Victory was being transformed into an angel carrying elaborate crosses and Chi-Rho-topped shafts.",
        "passage_source": "p. 5",
        "cultures": ["Byzantine", "Late Roman or Byzantine"],
        "date_range": [330, 1453],
        "topics": ["Byzantine coinage", "solidus", "Christian imagery", "Anastasios"],
        "week": 1,
        "description": "Traces the evolution of Byzantine coin iconography from Roman imperial types to Christian imagery, covering the solidus, follis, and key reform emperors.",
    },
    {
        "id": "haselgrove-2012",
        "authors": "C. Haselgrove and S. Krmnicek",
        "title": "The Archaeology of Money",
        "citation": "C. Haselgrove and S. Krmnicek, 'The Archaeology of Money,' Annual Review of Anthropology Vol. 41 (2012), pp. 235-250.",
        "file": "Archaeology of Money (1).pdf",
        "key_passage": "By unifying notions of value, symbolism, and fetish in a material form, monetary objects open up a multiplicity of viewpoints on the peoples who created and consumed them. In both classical studies and economics, coins are generally characterized by their inherent material properties as standardized objects — usually of metal, flat, and circular in shape, and issued (by an authority) for use as currency — emphasizing their political, economic, and technological dimensions. Coins are in fact just one specific form of money, if especially well developed for the purpose.",
        "passage_source": "p. 3",
        "cultures": [],
        "date_range": None,
        "topics": ["methodology", "archaeology", "money origins", "material culture"],
        "week": 1,
        "description": "Reviews archaeological evidence for money across cultures, examining how physical coins and proto-monetary objects illuminate ancient economies.",
    },

    # ── Week 2: Mesopotamia ──────────────────────────────────────────────────
    {
        "id": "powell-1996",
        "authors": "M.A. Powell",
        "title": "Money in Mesopotamia",
        "citation": "M.A. Powell, 'Money in Mesopotamia,' Journal of the Economic and Social History of the Orient 39/3 (1996), pp. 224-242.",
        "file": "Money in Mesopotamia (1).pdf",
        "key_passage": None,
        "passage_source": None,
        "cultures": ["Near Eastern", "Mesopotamian", "Assyrian"],
        "date_range": [-3000, -600],
        "topics": ["Mesopotamia", "pre-coin money", "silver weighed", "ancient Near East"],
        "week": 2,
        "description": "Examines the use of weighed silver and other commodities as proto-money in ancient Mesopotamia before the invention of coinage.",
    },
    {
        "id": "eagleton-williams-intro",
        "authors": "C. Eagleton and J. Williams",
        "title": "Money: Mesopotamia, Egypt, and Greece",
        "citation": "C. Eagleton and J. Williams, Money. A History (London: British Museum Press, 2007), pp. 16-23.",
        "file": "Money. Mesopotamia, Egypt, and Greece (1).pdf",
        "key_passage": None,
        "passage_source": None,
        "cultures": ["Near Eastern", "Egyptian", "Greek"],
        "date_range": [-3000, -300],
        "topics": ["money origins", "ancient economies", "Mesopotamia", "Egypt", "Greece"],
        "week": 2,
        "description": "Introductory survey of money's earliest forms across Mesopotamia, Egypt, and Greece, from commodity money to electrum coinage.",
    },

    # ── Week 3: Greek city-state coinage ────────────────────────────────────
    {
        "id": "howgego-1990",
        "authors": "C. Howgego",
        "title": "Why did Ancient States strike Coins?",
        "citation": "C. Howgego, 'Why did Ancient States strike Coins?' The Numismatic Chronicle Vol. 150 (1990), pp. 1-25.",
        "file": "Why_did_ancient_states_strike_coins (1).pdf",
        "key_passage": "Coinage was probably invented in order that a large number of state payments might be made in a convenient form and there is no reason to suppose that it was ever issued by Rome for any other purpose than to enable the state to make payments, that is, for financial reasons. And we have seen that in the cities of the Roman Empire, in striking contrast to the cities of the pre-Greek East, it acquired an important rôle as a means of exchange. But this monetary, economic function, like the other monetary functions of coinage, was an accidental consequence of the existence of coinage, not the reason for it.",
        "passage_source": "p. 2",
        "cultures": ["Greek", "Hellenistic", "Roman", "Persian"],
        "date_range": [-700, 300],
        "topics": ["coinage origins", "state authority", "political economy", "fiscal"],
        "week": 3,
        "description": "Foundational analysis of why ancient city-states began striking coins — examining fiscal, ideological, and commercial motivations across Greek and non-Greek mints.",
    },
    {
        "id": "martin-1996",
        "authors": "R. Martin",
        "title": "Why Did the Greek 'Polis' Originally Need Coins?",
        "citation": "R. Martin, 'Why Did the Greek \"Polis\" Originally Need Coins?' Historia 45/3 (1996), pp. 257-283.",
        "file": "What did the Greek Polis Need Coins (1).pdf",
        "key_passage": "The origins of coinage have been discussed since antiquity. Economic explanations were favoured for a long time, and have ancient authority. Thus Herodotus implies, and Aristotle states explicitly, that coinage was introduced in order to facilitate trade and retail trade. Cook looked at the origins of coinage in Asia Minor and suggested that it was the necessity of paying Greek mercenaries which brought about the first coins.",
        "passage_source": "p. 4",
        "cultures": ["Greek"],
        "date_range": [-700, -400],
        "topics": ["polis", "coinage origins", "archaic period", "city-state economy"],
        "week": 3,
        "description": "Investigates the economic and political conditions in archaic and classical Greek city-states that drove the adoption of coinage as civic identity and economic tool.",
    },
    {
        "id": "von-reden-1997",
        "authors": "S. von Reden",
        "title": "Money, Law and Exchange: Coinage in the Greek Polis",
        "citation": "S. von Reden, 'Money, Law and Exchange: Coinage in the Greek Polis,' The Journal of Hellenic Studies Vol. 117 (1997), pp. 154-176.",
        "file": "Money, Law, and Exchange in Ancient Greece (1).pdf",
        "key_passage": "It has long been recognised that money is both a reality and an ideology. Yet the interaction between the two, the extent to which all-purpose money, in ancient Greece first realised in the use of coinage, brings about particular ideologies of value and exchange, while at the same time being framed by them, rarely comes into focus. Warfare, religion, politics, market exchange and trade were all activities in which coinage was used. It required intimate cultural knowledge to understand the similarity and difference of their institutions and to recognise the different function and meanings of money within them.",
        "passage_source": "p. 2",
        "cultures": ["Greek"],
        "date_range": [-600, -200],
        "topics": ["Athens", "law", "exchange", "social meaning of money"],
        "week": 3,
        "description": "Argues that Athenian coins served symbolic and legal as well as economic functions; analyzes the nomos (law/convention) embedded in monetary circulation.",
    },
    {
        "id": "papadopoulos-2012",
        "authors": "J. Papadopoulos",
        "title": "Money, Art, and the Construction of Value",
        "citation": "J. Papadopoulos, 'Money, Art, and the Construction of Value' in J.K. Papadopoulos and G. Urton (eds.), The Construction of Value in the Ancient World (UCLA, 2012), pp. 261-87.",
        "file": "Money_art_and_the_construction_of_value (1) (1).pdf",
        "key_passage": "The earliest 'coins' were minted in western Anatolia, in Lydia and eastern Greece, sometime toward the end of the seventh century B.C. In searching for the origins of coinage, the specifics of the particular cultural context are of paramount importance. By boldly minting their identities on silver coinage, the Greek city-states chose money, the very vehicle of value, to create relations of dominance and to produce social orders that had not existed before.",
        "passage_source": "pp. 1–4",
        "cultures": ["Greek"],
        "date_range": [-700, -200],
        "topics": ["coin design", "artistic value", "imagery", "Greek art"],
        "week": 3,
        "description": "Explores how Greek coin imagery — goddesses, animals, heroes — participated in constructing and communicating cultural and economic value across the Mediterranean.",
    },

    # ── Week 4: Macedonia ───────────────────────────────────────────────────
    {
        "id": "kremmydi-2011",
        "authors": "S. Kremmydi",
        "title": "Coinage and Finance in Ancient Macedonia",
        "citation": "S. Kremmydi, 'Coinage and Finance,' in R. Lane Fox (ed.), Brill's Companion to Ancient Macedon (Leiden-Boston: Brill, 2011), pp. 159-178.",
        "file": None,
        "key_passage": None,
        "passage_source": None,
        "cultures": ["Macedonian", "Greek"],
        "date_range": [-400, -100],
        "topics": ["Philip II", "Alexander the Great", "Macedonian coinage", "royal finance"],
        "week": 4,
        "description": "Surveys Macedonian monetary production from Philip II through Alexander, examining how mass coinage financed military expansion and projected royal propaganda.",
    },

    # ── Week 5: Hellenistic world ────────────────────────────────────────────
    {
        "id": "de-callatay-2006",
        "authors": "F. de Callataÿ",
        "title": "The Fabulous Wealth of the Hellenistic Kings",
        "citation": "F. de Callataÿ, 'The Fabulous Wealth of the Hellenistic Kings' in Words and Coins: From Ancient Greece to Byzantium, pp. 91-101.",
        "file": "The_fabulous_wealth_of_the_Hellenistic_k (1).pdf",
        "key_passage": "It was to pay the soldiers that the precious metal was originally converted into coins, just as Alexander's father, Philip, had done when he took over the Crenides mines. One hundred and twenty thousand talents did in fact represent a sum never seen before in the Greek and Mediterranean world: some 3,100 tons of silver — that is, almost the total yield of the Laurion mines yielded in more than two centuries of exploitation — or 720 million drachmas, enough to pay 100,000 men one drachma a day for 20 years.",
        "passage_source": "p. 5",
        "cultures": ["Hellenistic", "Seleucid", "Ptolemaic", "Greek", "Macedonian"],
        "date_range": [-323, -31],
        "topics": ["Hellenistic kings", "royal wealth", "successor states", "coinage volume"],
        "week": 5,
        "description": "Reconstructs the extraordinary monetary wealth of Hellenistic successor kingdoms and how mass coin production by the Ptolemies, Seleucids, and others transformed Mediterranean economics.",
    },
    {
        "id": "meadows-2014",
        "authors": "A. Meadows",
        "title": "The Spread of Coins in the Hellenistic World",
        "citation": "A. Meadows, 'The Spread of Coins in the Hellenistic World' in P. Bernholz and R. Vaubel (eds.), Explaining Monetary and Financial Innovation (2014), pp. 169-194.",
        "file": "The_spread_of_coins_in_the_Hellenistic_w-1 (1).pdf",
        "key_passage": "Although coinage was first 'invented' in the archaic Greek period, and spread to a significant part of the Mediterranean world during the classical period, it remained a marginal element within the economy. Significant changes in the nature and scale of coinage occurred only in the wake of Alexander's world conquest, during the Hellenistic period.",
        "passage_source": "p. 1",
        "cultures": ["Hellenistic", "Seleucid", "Ptolemaic", "Greek"],
        "date_range": [-323, -31],
        "topics": ["monetary spread", "Hellenistic economy", "coinage zones", "financial innovation"],
        "week": 5,
        "description": "Traces how Greek coinage spread from a handful of mints in the 6th century to cover the entire Hellenistic world after Alexander, creating interconnected monetary zones.",
    },
    {
        "id": "georganteli-2012-egypt",
        "authors": "E. Georganteli",
        "title": "Economy and Art in Egypt from Alexander",
        "citation": "E. Georganteli, 'Economy and Art in Egypt from Alexander' in E. Georganteli and M. Bommas (eds.), Sacred and Profane: Treasures of Ancient Egypt (London: D Giles Publishers), pp. 101-120.",
        "file": "Economy and Art in Egypt (1).pdf",
        "key_passage": "Among Ptolemy I's initial steps to legitimize his claim over Egypt were his efforts to secure the body of Alexander for Egypt, and to strike high-quality silver coins bearing images of the deified Alexander. On one of the first issues struck in the mint of Alexandria, Alexander appears on the obverse wearing an elephant scalp with trunks and tusks and a royal diadem. The inclusion in the headdress of the ram's horn of Zeus Ammon conveys Alexander's public persona as son of Zeus Ammon following his visit to the oracle of Ammon in the Siwa desert.",
        "passage_source": "pp. 2–3",
        "cultures": ["Ptolemaic", "Egyptian", "Hellenistic"],
        "date_range": [-323, -30],
        "topics": ["Ptolemaic Egypt", "Hellenistic economy", "Alexandria", "art and money"],
        "week": 5,
        "description": "Examines the Ptolemaic monetary economy of Egypt — closed currency zone, grain-backed coinage — and its visual culture blending Greek and Egyptian artistic traditions.",
    },

    # ── Week 6: Athenian economy / Delian League ─────────────────────────────
    {
        "id": "gardner-1913",
        "authors": "P. Gardner",
        "title": "Coinage of the Athenian Empire",
        "citation": "P. Gardner, 'Coinage of the Athenian Empire,' The Journal of Hellenic Studies 33 (1913), pp. 147-188.",
        "file": "Coinage of the Athenian Empire.pdf",
        "key_passage": "The Athenians obtained silver in abundance from the mines of Laurium and those of Thrace, and it was part of Athenian policy to circulate the coins as widely as possible, and to make them the standard currency of the Aegean. Silver was to Athens what gold was to Persia, the backbone of the finance of the state. A head of Athena and an owl of fixed and conventional archaic type had been adopted for the coin; the Athenians seem to have felt that they expressed the personality of their city, and so they clung to them with a conservatism remarkable even in the history of coinage.",
        "passage_source": "p. 2",
        "cultures": ["Greek"],
        "date_range": [-480, -404],
        "topics": ["Delian League", "Athenian empire", "owl tetradrachm", "monetary hegemony"],
        "week": 6,
        "description": "Classic study of Athenian coinage during the imperial period; analyzes how the owl tetradrachm became the de facto currency of the Athenian empire.",
    },
    {
        "id": "robinson-1949",
        "authors": "E.S.G. Robinson",
        "title": "The Athenian Currency Decree and the Coinages of the Allies",
        "citation": "E.S.G. Robinson, 'The Athenian Currency Decree and the Coinages of the Allies,' Hesperia Supplements Vol. 8 (1949), pp. 324-340.",
        "file": "Athens and the Currency Decree.pdf",
        "key_passage": "The purpose of the decree is twofold: it was to prevent (i) the striking of silver coins in the cities; (ii) the use of currency, weights, and measures other than Athenian. In the first half of the fifth century the currency circulating within the area of the League must still have been of a very heterogeneous nature, with a preponderance, steadily diminishing, of non-Athenian money. The mass of Aeginetan money still circulating was a continual reminder of Aegina's recent greatness, a continual irritation to Athens.",
        "passage_source": "pp. 2–3",
        "cultures": ["Greek"],
        "date_range": [-450, -404],
        "topics": ["Athenian Currency Decree", "allied coinage", "monetary imperialism"],
        "week": 6,
        "description": "Analyzes the Athenian Currency Decree that required allies to use Athenian silver, examining how monetary policy served Athenian imperial control.",
    },
    {
        "id": "kallet-1989",
        "authors": "L. Kallet",
        "title": "Did Tribute Fund the Parthenon?",
        "citation": "L. Kallet, 'Did Tribute fund the Parthenon?' Classical Antiquity 8/2 (1989), pp. 252-266.",
        "file": "Did_Tribute_Fund_the_Parthenon.pdf",
        "key_passage": None,
        "passage_source": None,
        "cultures": ["Greek"],
        "date_range": [-450, -430],
        "topics": ["Parthenon", "Delian League", "tribute", "public finance"],
        "week": 6,
        "description": "Investigates the financial relationship between Delian League tribute and Athenian public building, questioning whether allied tribute directly funded the Parthenon.",
    },

    # ── Week 7: Roman Republic ───────────────────────────────────────────────
    {
        "id": "morel-2007",
        "authors": "J.-P. Morel",
        "title": "Early Italy and the Roman Republic",
        "citation": "J.-P. Morel, 'Early Italy and the Roman Republic' in W. Scheidel, I. Morris, and R. Saller (eds.), The Cambridge Economic History of the Greco-Roman World (Cambridge University Press, 2007), pp. 487-510.",
        "file": "early_rome_and_italy.pdf",
        "key_passage": "Magna Graecia bestowed on Italy in general and Rome in particular, either directly or via the Etruscans, the potter's wheel, olive oil and probably wine, and perhaps large-scale grain cultivation, as well as preconditions of economic growth such as ports, writing, coinage (adopted shortly after its emergence in the Aegean, around 550 BC), and perhaps banking techniques.",
        "passage_source": "pp. 8–11",
        "cultures": ["Roman", "Roman Republican"],
        "date_range": [-300, -27],
        "topics": ["Roman Republican economy", "early Rome", "monetization", "Italy"],
        "week": 7,
        "description": "Surveys the economic development of Republican Rome and Italy, including the emergence of bronze and silver coinage as Rome expanded across the peninsula.",
    },
    {
        "id": "de-rose-evans-1992",
        "authors": "J. DeRose Evans",
        "title": "The Art of Persuasion: Coins and Propaganda in Republican Rome",
        "citation": "J. DeRose Evans, The Art of Persuasion: Political Propaganda from Aeneas to Brutus (Ann Arbor: University of Michigan Press, 1992), chapter 2 (Coins and Propaganda).",
        "file": "The Art of Persuasion in the Roman world (1).pdf",
        "key_passage": None,
        "passage_source": None,
        "cultures": ["Roman", "Roman Republican"],
        "date_range": [-300, -27],
        "topics": ["Republican denarius", "propaganda", "moneyers", "coin imagery", "ancestor"],
        "week": 7,
        "description": "Examines how Republican moneyers used denarius reverses to display family achievements, mythological ancestors, and historical events as political propaganda.",
    },
    {
        "id": "meadows-williams-2001",
        "authors": "A. Meadows and J. Williams",
        "title": "Moneta and the Monuments: Coinage and Politics in Republican Rome",
        "citation": "A. Meadows and J. Williams, 'Moneta and the Monuments: Coinage and Politics in Republican Rome,' The Journal of Roman Studies Vol. 91 (2001), pp. 27-49.",
        "file": "Moneta and the Monuments- Coinage and Politics in Republican Rome.pdf",
        "key_passage": "The mint of Republican Rome was located on the Capitol somewhere in the vicinity of the temple of Juno Moneta. The goddess and her temple seem to have been associated with the standard of the official Roman unit of length, the foot — known by the technical name pes monetalis, the 'monetal foot' — suggesting that Juno Moneta was regarded as one of the guardians of the Roman unit of length. The standards of length and monetary weight maintained by Moneta applied beyond the confines of her precinct, becoming standard terms of measurement in Rome and beyond.",
        "passage_source": "pp. 2–4",
        "cultures": ["Roman", "Roman Republican"],
        "date_range": [-200, -27],
        "topics": ["Republican coinage", "monuments", "Capitoline", "political competition"],
        "week": 7,
        "description": "Argues that late Republican moneyers systematically depicted monuments and civic structures on coin reverses as tools in aristocratic competition for political prestige.",
    },

    # ── Week 8: Roman Empire ─────────────────────────────────────────────────
    {
        "id": "howgego-1992",
        "authors": "C. Howgego",
        "title": "The Supply and Use of Money in the Roman World 200 BC–AD 300",
        "citation": "C. Howgego, 'The Supply and Use of Money in the Roman World 200 B.C. to A.D. 300,' The Journal of Roman Studies Vol. 82 (1992), pp. 1-31.",
        "file": "The Supply and Use of Money in the Roman World-1 (1).pdf",
        "key_passage": "The period is characterized by a reasonably abundant coinage based on the (at least notionally) silver denarius, with significant issues of gold coin from 46 B.C. onwards, and a fiduciary base metal coinage. The denarius became by stages a world coinage, both by an increase in its area of circulation, and by the adaptation of other coinage systems so that they became compatible with the denarius. From the first century A.D. onwards, and dramatically in the third century, the precious metal content of the coinage declined through reductions in weight or debasements.",
        "passage_source": "p. 3",
        "cultures": ["Roman", "Roman Imperial", "Roman Republican", "Roman Provincial"],
        "date_range": [-200, 300],
        "topics": ["money supply", "coinage circulation", "Roman economy", "denarius", "debasement"],
        "week": 8,
        "description": "Comprehensive analysis of Roman monetary supply and circulation across five centuries, tracing how coinage was produced, distributed, and used throughout the empire.",
    },
    {
        "id": "levick-1999",
        "authors": "B. Levick",
        "title": "Messages on the Roman Coinage: Types and Inscriptions",
        "citation": "B. Levick, 'Messages on the Roman Coinage: Types and Inscriptions' in G.M. Paul (ed.), Roman Coins and Public Life under the Empire (Ann Arbor: University of Michigan Press, 1999), pp. 41-60.",
        "file": "B LEVICK MESSAGES ON THE ROMAN COINS (1) (1).pdf",
        "key_passage": None,
        "passage_source": None,
        "cultures": ["Roman", "Roman Imperial"],
        "date_range": [-27, 400],
        "topics": ["imperial propaganda", "emperor portraits", "coin legends", "types", "reverse"],
        "week": 8,
        "description": "Analyzes how Roman emperors used coin legends and reverse types as mass media to broadcast dynastic legitimacy, military victories, and imperial ideology.",
    },
    {
        "id": "burnett-2011",
        "authors": "A. Burnett",
        "title": "The Augustan Revolution seen from the Mints of the Provinces",
        "citation": "A. Burnett, 'The Augustan Revolution seen from the Mints of the Provinces,' The Journal of Roman Studies 101 (2011), pp. 1-30.",
        "file": "the-augustan-revolution-seen-from-the-mints-of-the-provinces (1) (1).pdf",
        "key_passage": "Provincial coinage typically featured a portrait of the emperor or an empress on the obverse side and an image, often religious, on the reverse side that referred to the issuing city in some way. The material and iconographic changes to provincial coinages can provide further insights into the transformations that were taking place, from the point of view of those civic élites of the Empire who were responsible for their production.",
        "passage_source": "pp. 1–3",
        "cultures": ["Roman", "Roman Imperial", "Roman Provincial"],
        "date_range": [-27, 14],
        "topics": ["Augustus", "Augustan coinage", "provincial mints", "monetary reform"],
        "week": 8,
        "description": "Examines how Augustan monetary reforms unified Roman coinage across provincial mints, transforming coin types into instruments of the new Principate's ideology.",
    },

    # ── Week 9: Byzantine ────────────────────────────────────────────────────
    {
        "id": "lopez-1951",
        "authors": "R.S. Lopez",
        "title": "The Dollar of the Middle Ages",
        "citation": "R.S. Lopez, 'The Dollar of the Middle Ages,' The Journal of Economic History 11/3 (Summer 1951), pp. 209-234.",
        "file": "Lopez-DollarMiddleAges-1951-1 (1).pdf",
        "key_passage": "The gold money of the Byzantine Empire 'is accepted everywhere from end to end of the earth. It is admired by all men and in all kingdoms, because no kingdom has a currency that can be compared to it.' The gold nomisma (or bezant, as the Westerners later called it) was as peerless as the sovereign whose effigy it bore. The bezant outstripped the dollar in stability and intrinsic value; its record has never been equaled or even approached by any other currency — the daric and the aureus, the florin and the ducat, the dobla and the guinea all had their periods of glory, but none of them preserved the original standard for such a long time.",
        "passage_source": "pp. 2–4",
        "cultures": ["Byzantine"],
        "date_range": [330, 1100],
        "topics": ["solidus", "nomisma", "international currency", "medieval trade"],
        "week": 9,
        "description": "The classic argument that the Byzantine gold solidus served as the dollar of the medieval world — stable international reserve currency from Constantine to the 11th-century debasement.",
    },
    {
        "id": "morrisson-2017",
        "authors": "C. Morrisson",
        "title": "One Money for an Empire: Byzantine Currency",
        "citation": "C. Morrisson, 'One Money for an Empire: Achievements and Limitations of Byzantium's Currency' in G. Notaras (ed.), From the Athenian Tetradrachm to the Euro (Routledge, 2017), pp. 23-40.",
        "file": "Morrisson One Money (1).pdf",
        "key_passage": None,
        "passage_source": None,
        "cultures": ["Byzantine"],
        "date_range": [330, 1453],
        "topics": ["monetary policy", "solidus", "follis", "Constantine", "debasement"],
        "week": 9,
        "description": "Traces Byzantine monetary policy across eleven centuries, examining the solidus's remarkable stability and the debasement crisis that led to Alexios I's coinage reform.",
    },
    {
        "id": "georganteli-byzantine-coins",
        "authors": "E. Georganteli",
        "title": "Byzantine Coins (in Byzantium, Royal Academy of Arts)",
        "citation": "E. Georganteli, 'Byzantine Coins' in R. Cormack and M. Vassilaki (eds.), Byzantium (London: Royal Academy of Art, 2008).",
        "file": "Byzantine_Coins_in_R_Cormack_and_M_Vass (2).pdf",
        "key_passage": None,
        "passage_source": None,
        "cultures": ["Byzantine"],
        "date_range": [330, 1453],
        "topics": ["Byzantine coin types", "art history", "solidus", "exhibition catalog"],
        "week": 9,
        "description": "Catalog essay on Byzantine coins as artistic objects, covering iconographic programs from the early Byzantine period through the final centuries.",
    },

    # ── Week 10: Islamic coinage ─────────────────────────────────────────────
    {
        "id": "wasserstein-1993",
        "authors": "J. Wasserstein",
        "title": "Coins as Agents of Cultural Definition in Islam",
        "citation": "J. Wasserstein, 'Coins as Agents of Cultural Definition in Islam,' Poetics Today 14/2 (Summer 1993), pp. 303-322.",
        "file": "Coins as Agents of Cultural Definition in Islam.pdf",
        "key_passage": "Every element in the makeup of a coin, from its material through its design, fabric, script, language, textual expression, and general content, has a part to play in this and makes a statement on the overt, literal level as well as on other levels. The cumulative effect of all this is to create a numismatic metalanguage which serves to define Islamic coins as Islamic (and therefore, by extension, also to define non-Islamic coins as non-Islamic). The boundaries thus defined and erected are part of the overall cultural definition of the medieval Islamic world.",
        "passage_source": "p. 2",
        "cultures": ["Islamic", "Arab", "Umayyad", "Abbasid", "Arabo-Byzantine"],
        "date_range": [600, 1400],
        "topics": ["Islamic reform", "aniconic", "Quranic inscriptions", "caliphate legitimacy"],
        "week": 10,
        "description": "Analyzes Abd al-Malik's 696 CE monetary reform that removed figural imagery and introduced Quranic inscriptions, forging a distinctively Islamic visual identity on coins.",
    },
    {
        "id": "natif-2019",
        "authors": "M. Natif",
        "title": "Painters will be Punished: Figural Representation Among the Umayyads",
        "citation": "M. Natif, 'Painters will be Punished — The Politics of Figural Representation Amongst the Umayyads' in C. Gruber (ed.), The Image Debate (London: Gingko, 2019), pp. 32-45.",
        "file": "Painters_will_be_Punished_The_Politics.pdf",
        "key_passage": "Some coins inscribed with the shahada or other religious phrases from the years 693–96 CE also include an image of the caliph. On these coins, the caliph is usually represented bearded, with long hair, standing, wearing a robe and holding the hilt of a sword. The figure of the caliph on the coin is flanked by two Arabic inscriptions: one gives his title amir al-mu'minin (Commander of the Faithful), while the other declares him khalifat Allah — bringing together the image of the Umayyad ruler as a military commander, as protector of the faith and as a religious authority in his position as deputy of God on earth.",
        "passage_source": "p. 8",
        "cultures": ["Islamic", "Umayyad", "Arab", "Arabo-Byzantine"],
        "date_range": [660, 750],
        "topics": ["Umayyad coinage", "figural imagery", "caliph portrait", "standing caliph"],
        "week": 10,
        "description": "Examines the brief appearance of caliph portraits on Umayyad coins before Abd al-Malik's aniconic reform, and the politics of figural representation in early Islam.",
    },
    {
        "id": "walmsley-2010",
        "authors": "A. Walmsley",
        "title": "Coinage and the Economy of Syria-Palestine in the 7th–8th Centuries",
        "citation": "A. Walmsley, 'Coinage and the Economy of Syria-Palestine in the Seventh and Eighth Centuries CE' in J. Haldon (ed.), Money, Power and Politics in Early Islamic Syria (Farnham: Ashgate, 2010), pp. 21-44.",
        "file": "Money in Syria after the Islamic Conquest-2.pdf",
        "key_passage": None,
        "passage_source": None,
        "cultures": ["Islamic", "Arab", "Umayyad", "Byzantine", "Arabo-Byzantine"],
        "date_range": [600, 800],
        "topics": ["Syria-Palestine", "Umayyad", "early Islamic economy", "transition"],
        "week": 10,
        "description": "Examines the monetary transition from Byzantine to Islamic coinage in Syria-Palestine, tracing the persistence of Byzantine coin types in early Arab-Byzantine issues.",
    },
    {
        "id": "georganteli-2012-transposed",
        "authors": "E. Georganteli",
        "title": "Transposed Images: Currencies and Legitimacy in the Late Medieval Eastern Mediterranean",
        "citation": "E. Georganteli, 'Transposed Images: Currencies and Legitimacy in the Late Medieval Eastern Mediterranean,' in J. Harris, C. Holmes and E. Russell (eds.), Byzantines, Latins, and Turks in the Eastern Mediterranean World after 1150 (Oxford: Oxford University Press, 2012), pp. 141-79.",
        "file": "Transposed images. Money and Identity in the Medieval Mediterranean (1).pdf",
        "key_passage": "Between the eleventh and the fourteenth centuries secular and religious images appeared in the coinage of Muslim rulers of Anatolia, nearly four centuries after the last figural Islamic coins were struck by Abd al-Malik. Among the motifs, a Muslim take on a silver tetradrachm of the Hellenistic ruler Antiochos VIII, created by the twelfth-century Artuqids of Mardin, should be interpreted as part of an overall quest by Turkish rulers for continuity and legitimacy, based on Anatolia's pre-Islamic past.",
        "passage_source": "pp. 3–4",
        "cultures": ["Byzantine", "Islamic", "Crusader", "Latin"],
        "date_range": [1150, 1453],
        "topics": ["imitation coinage", "legitimacy", "cross-cultural exchange", "Crusader"],
        "week": 10,
        "description": "Examines how Byzantine, Islamic, and Crusader rulers imitated each other's coin designs to claim political legitimacy across the contested eastern Mediterranean after 1150.",
    },

    # ── Week 11: Medieval European coinage ──────────────────────────────────
    {
        "id": "eagleton-williams-medieval",
        "authors": "C. Eagleton and J. Williams",
        "title": "Money in Medieval and Early Modern Europe",
        "citation": "C. Eagleton and J. Williams, Money. A History (London: British Museum Press, 2007), pp. 62-85.",
        "file": "Coinage in Medieval and Early Modern Europe.pdf",
        "key_passage": None,
        "passage_source": None,
        "cultures": ["Medieval European", "British", "French", "German", "Italian"],
        "date_range": [400, 1500],
        "topics": ["medieval coinage", "Charlemagne", "penny", "denier", "feudal economy"],
        "week": 11,
        "description": "Surveys medieval European coinage from the fall of Rome to Charlemagne's monetary reform and beyond, covering the penny/denier standard and regional monetary fragmentation.",
    },
    {
        "id": "money-coinage-medieval",
        "authors": "Various",
        "title": "Money and Coinage in the Middle Ages",
        "citation": "Money and Coinage in the Middle Ages, chapter 4 (From the Fall of Rome to Charlemagne, c.400–800).",
        "file": "Money and Coinage in medieval Europe.pdf",
        "key_passage": None,
        "passage_source": None,
        "cultures": ["Medieval European"],
        "date_range": [400, 800],
        "topics": ["post-Roman coinage", "Charlemagne", "dark ages money", "denier"],
        "week": 11,
        "description": "Covers the monetary fragmentation following Rome's fall and Charlemagne's reforms that established the penny/denier as the standard medieval European coin.",
    },
]

# ── Matching helpers ─────────────────────────────────────────────────────────

READINGS_BY_ID = {r["id"]: r for r in READINGS}

_CULTURE_MAP = {}
for _r in READINGS:
    for _c in _r["cultures"]:
        _CULTURE_MAP.setdefault(_c.lower(), []).append(_r["id"])

_BROAD_CULTURE_MAP = {
    "roman provincial": ["Roman", "Roman Imperial"],
    "roman imperial": ["Roman"],
    "roman republican": ["Roman"],
    "late roman or byzantine": ["Roman", "Byzantine"],
    "hellenistic or early roman": ["Hellenistic", "Greek"],
    "hellenistic": ["Greek"],
    "graeco-roman": ["Greek", "Roman"],
    "indo-greek": ["Hellenistic"],
    "seleucid": ["Hellenistic"],
    "ptolemaic": ["Hellenistic"],
    "macedonian": ["Macedonian", "Greek"],
    "arabo-byzantine": ["Byzantine", "Islamic"],
    "umayyad": ["Islamic"],
    "abbasid": ["Islamic"],
    "byzantine?": ["Byzantine"],
    "greek?": ["Greek"],
}


def candidate_readings_for(cultures: list[str], query: str = "") -> list[dict]:
    seen = set()
    candidates = []

    for culture in cultures:
        cl = culture.lower()
        for rid in _CULTURE_MAP.get(cl, []):
            if rid not in seen:
                seen.add(rid)
                candidates.append(READINGS_BY_ID[rid])
        for alias in _BROAD_CULTURE_MAP.get(cl, []):
            for rid in _CULTURE_MAP.get(alias.lower(), []):
                if rid not in seen:
                    seen.add(rid)
                    candidates.append(READINGS_BY_ID[rid])

    if not candidates:
        for r in READINGS:
            if not r["cultures"] and r["id"] not in seen:
                seen.add(r["id"])
                candidates.append(r)

    return candidates
